# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
   # #Nome da Imagem que será baixada
   config.vm.box = "debian/bookworm64"
   config.vm.box_check_update = false #Verificar o update da vbox
   config.vm.network "private_network", ip: "192.168.33.11" #Definindo o tipo de rede e um ip para a máquina virtual
   config.vm.synced_folder "files", "/files" #
  
   config.vm.provider "virtualbox" do |vb| #Configuração da máquina virtual que será criada
    
      nomeMaquina="DebianLuks"
      sdb = "E:\disk\dluksSdb.vdi"
      sdc = "E:\disk\dluksSdc.vdi"
      vb.customize ['createhd', '--filename', sdb, '--size', 10 * 1024]
      vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', sdb]
      vb.customize ['createhd', '--filename', sdc , '--size', 20 * 1024]
      vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', sdc]
      vb.name = nomeMaquina #Definindo o nome da Máquina
      vb.cpus = 2 
      vb.gui = false 
      vb.memory = "2024" 
      vb.customize ["modifyvm", :id, "--groups", "/Lpic3"]
   end
   config.vm.provision "shell", inline: <<-SHELL #executando update do Debian durante o provisionamento. 
     hostnamectl set-hostname DebianLuks
     apt-get update -y
     apt install -y xfsprogs
   SHELL
   # config.vm.provision "shell", path:"files/makedb.sh"
end
